apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
      release: prometheus
  template:
    metadata:
      labels:
        app: backend
        release: prometheus
    spec:
      containers:
      - name: backend
        image: devhernandez2/metric_dash_backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
spec:
  selector:
    app: backend
  ports:
    - name: backend
      protocol: TCP
      port: 8081
      targetPort: backendport
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default



    