apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
      release: prometheus
  template:
    metadata:
      labels:
        app: frontend
        release: prometheus
    spec:
      containers:
      - name: frontend
        image: devhernandez2/metric_dash_frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    app: frontend
    release: prometheus
  ports:
    - name: frontend
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
  - port: frontend
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default