apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability
  namespace: monitoring
  labels:
    app: backend
    release: prometheus
spec:
  selector:
    matchLabels:
      release: prometheus
  endpoints:
  - port: backend
    path: /metrics
    interval: 15s
  - port: frontend
    path: /metrics
    interval: 15s
  - port: trial
    path: /metrics
    interval: 15s
  namespaceSelector:
    matchNames:
    - default